/**
 * Banked data loading utility routines.
 */

#ifndef _DATA_H
#define _DATA_H

#include <gb/gb.h>
#include <gbdk/incbin.h>

// Banked data externs
// TODO This should be automatically generated by a compiler script

INCBIN_EXTERN(tilemap_textbox)
INCBIN_EXTERN(tilemap_title_screen)
INCBIN_EXTERN(tilemap_name_entry)
INCBIN_EXTERN(tilemap_save_select)
INCBIN_EXTERN(tilemap_battle_menus)
INCBIN_EXTERN(tilemap_battle_monster_layouts)

INCBIN_EXTERN(tile_data_dungeon)
INCBIN_EXTERN(tile_data_font)
INCBIN_EXTERN(tile_battle)
INCBIN_EXTERN(tile_data_hero)
INCBIN_EXTERN(tile_data_objects)

INCBIN_EXTERN(map_example_0)
INCBIN_EXTERN(map_example_1)

INCBIN_EXTERN(tile_kobold)
INCBIN_EXTERN(tile_beholder)

#endif
